### ISSUE TITLE
Problems with React.js

### ISSUE THREAD

**Issue by timse** [marmelab/gremlins.js#88] opened 2015-05-07 10:44 UTC
gremlins.js seems to have problems with React.js - we can't seem to get it to trigger any event listeners (onChange, onClick, etc.) - any ideas?

**Comment by jpetitcolas** [comment] 2015-05-07 12:00
Indeed, I got the same issue. I'm looking at it.

**Comment by Dashed** [comment] 2015-05-22 14:04
I can confirm.

**Comment by riston** [comment] 2015-10-27 14:28
The problem is that the React has it's own Synthetic events which does not trigger any change. React also provides event simulator https://github.com/facebook/react/blob/master/src/test/ReactTestUtils.js#L470, but it's tightly coupled with other components.

**Comment by barbuza** [comment] 2016-02-12 13:53
FYI https://gist.github.com/barbuza/5c0aac86a526306c4003

**Comment by fzaninotto** [comment] 2016-02-23 10:37
@barbuza awesome. Would you like to open a PR on this repository with your React clicker gremlin?

**Comment by Sudarson59** [comment] 2018-02-03 12:39
@fzaninotto @barbuza It would really nice if gremlin.js provides support for testing react storybook stories.
Any idea about supporting react-storybook stories.

**Comment by HALLERPierre** [comment] 2020-04-22 08:36
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.

**Closed by HALLERPierre** 2020-04-22 08:36 UTC
Labels: hacktoberfest
